WIDTH = 800
HEIGHT = 600
ARENA_WIDTH = 1600
ARENA_HEIGHT = 1200
DOT_RADIUS = 10
SPEED = 220
DIFFICULTY_EASY = 0
DIFFICULTY_NORMAL = 1
DIFFICULTY_HARD = 2
DIFFICULTY_NAMES = {
    DIFFICULTY_EASY: "Easy",
    DIFFICULTY_NORMAL: "Normal",
    DIFFICULTY_HARD: "Hard",
}
ENEMY_RADIUS = DOT_RADIUS
ENEMY_SPEED = 200
ENEMY_TARGET_SECONDS = 4
ENEMY_BASE_SPAWN_SECONDS = 2.4
ENEMY_SPAWN_SPEED_STEP = 0.35
ENEMY_SPEED_STEP = 0.25
INDICATOR_LENGTH = 20
HEALTH = 3
BLINK_SECONDS = 2
RESPAWN_SECONDS = 2
BULLET_RADIUS = 4
BULLET_SPEED = 420
BULLET_LIFETIME = 1.5
ROUNDS_PER_SECOND = 5
SHOT_INTERVAL_SECONDS = 1 / ROUNDS_PER_SECOND
FPS = 60
SERVER_HOST = "0.0.0.0"
CLIENT_HOST = "0.0.0.0"
